//
export const GET_MUSIC_DETAILS_LOADING = "GET_MUSIC_DETAILS_LOADING";
export const GET_MUSIC_DETAILS_SUCCESS = "GET_MUSIC_DETAILS_SUCCESS";
export const GET_MUSIC_DETAILS_ERROR = "GET_MUSIC_DETAILS_ERROR";
//
export const ADD_MUSIC_DETAILS_LOADING = "ADD_MUSIC_DETAILS_LOADING";
export const ADD_MUSIC_DETAILS_SUCCESS = "ADD_MUSIC_DETAILS_SUCCESS";
export const ADD_MUSIC_DETAILS_ERROR = "ADD_MUSIC_DETAILS_ERROR";
//
export const UPDATE_MUSIC_DETAILS_LOADING = "UPDATE_MUSIC_DETAILS_LOADING";
export const UPDATE_MUSIC_DETAILS_SUCCESS = "UPDATE_MUSIC_DETAILS_SUCCESS";
export const UPDATE_MUSIC_DETAILS_ERROR = "UPDATE_MUSIC_DETAILS_ERROR";
//
export const DELETE_MUSIC_DETAILS_LOADING = "DELETE_MUSIC_DETAILS_LOADING";
export const DELETE_MUSIC_DETAILS_SUCCESS = "DELETE_MUSIC_DETAILS_SUCCESS";
export const DELETE_MUSIC_DETAILS_ERROR = "DELETE_MUSIC_DETAILS_ERROR";